title: Python_datascience_learning
description: Hi i am here learning data science using python
template:
  repo: python_datascience_learning-template
  name: python_datascience_learning
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
